name: Build

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version-file: '.node-version'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn --frozen-lockfile

      - name: Run linter
        run: yarn lint

      - name: Run build
        run: yarn build

      - name: Test codebase
        run: yarn test

# Here I would usually add a matrix to deploy using Terraform, but I'm getting way-ahead-of-myself here